import { Service } from './Models/service.model';

export const SERVICES: Service[] = [
  { id: 1, name: 'Auto', desc: '', img: '../assets/images/auto.jpg', keywords: ['car', 'auto'], isUsed: false, suggestedIds:[8] },
  { id: 2, name: 'Aviation', desc: '', img: '../assets/images/aviation.jpg', keywords: ['plane', 'aviation'], isUsed: false, suggestedIds:[]},
  { id: 3, name: 'Collectibles', desc: '', img: '../assets/images/collectible.jpg', keywords: ['collection', 'collectibles'], isUsed: false, suggestedIds:[10]},
  { id: 4, name: 'Farm & Ranch', desc: '', img: '../assets/images/farm-and-ranch.jpg', keywords: ['farm', 'ranch','barn','stable'], isUsed: false, suggestedIds:[]},
  { id: 5, name: 'Mobile Device', desc: '', img: '../assets/images/mobile-device.jpg', keywords: ['cellphone', 'mobile', 'device'], isUsed: false, suggestedIds: [] },
  { id: 6, name: 'Pet Health', desc: '', img: '../assets/images/pet-health.jpg', keywords: ['pet', 'dog', 'cat'], isUsed: false, suggestedIds: []},
  { id: 7, name: 'Rental Property', desc: '', img: '../assets/images/rental-property.jpg', keywords: ['rental', 'rent', 'renter'], isUsed: false, suggestedIds:[] },
  { id: 8, name: 'Motorcycles', desc: '', img: '../assets/images/motorcycle.jpg', keywords: ['motorcycle'], isUsed: false, suggestedIds:[1] },
  { id: 9, name: 'Watercraft', desc: '', img: '../assets/images/watercraft.jpg', keywords: ['watercraft', 'boat', 'yacht','jet', 'ski'], isUsed: false, suggestedIds:[12] },
  { id: 10, name: 'Life Insurance', desc: '', img: '../assets/images/life-insurance.jpg', keywords: ['marriage', 'married'], isUsed: false, suggestedIds:[3, 16] },
  { id: 11, name: 'Home Insurance', desc: '', img: '../assets/images/home-insurance-large.jpeg', keywords: ['house', 'home', 'homeowner'], isUsed: false, suggestedIds:[14, 15]},
  { id: 12, name: 'Florida', desc: '', img: '../assets/images/florida-property.jpg', keywords: ['florida'], isUsed: false, suggestedIds:[13, 9, 11]},
  { id: 13, name: 'Flood', desc: '', img: '../assets/images/flood.jpg', keywords: ['flood', 'flooding'], isUsed: false, suggestedIds:[12]},
  { id: 14, name: 'Renters Insurance', desc: '', img: '../assets/images/renters-insurance.jpg', keywords: ['rent', 'renter','renting'], isUsed: false, suggestedIds:[11]},
  { id: 15, name: 'High Value Home', desc: '', img: '../assets/images/high-value-home.jpg', keywords: ['high', 'value'], isUsed: false, suggestedIds:[11]},
  { id: 16, name: 'Jewelry Insurance', desc: '', img: '../assets/images/jewerly-insruance.jpg', keywords: ['jewelry'], isUsed: false, suggestedIds:[10]},
  { id: 15, name: 'Cruises', desc: '', img: '../assets/images/cruises.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 16, name: 'Flights', desc: '', img: '../assets/images/flights.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 14, name: 'Hotels & Resorts', desc: '', img: '../assets/images/hotels-and-resorts.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 17, name: 'Travel Insurance', desc: '', img: '../assets/images/travel-insurance.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 18, name: 'Home Security', desc: '', img: '../assets/images/home-security.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 19, name: 'Moving & Storage', desc: '', img: '../assets/images/moving.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 20, name: 'Flowers', desc: '', img: '../assets/images/ftd_bingo.png', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 21, name: 'FedEx', desc: '', img: '../assets/images/shipping.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 22, name: 'TurboTax', desc: '', img: '../assets/images/tax-preparation.jpg', keywords: [''], isUsed: false, suggestedIds:[12]},
  { id: 23, name: 'Car Rentals', desc: '', img: '../assets/images/car-rental.jpg', keywords: [''], isUsed: false, suggestedIds:[12]}
];
